### ISSUE TITLE
compiled version

### ISSUE THREAD

**Issue by 097115** [kykim/rem#2]
Could you please provide a build? Installing Xcode only because of rem seems a bit extreme :).

**Comment by jhirbour** [comment]
Could you provide basic instructions for compiling it? Maybe we can add this as a homebrew package?

**Comment by thaaophz** [comment]
Maybe #9 can help you.

**Comment by kykim** [comment]
I've created a homebrew formula [here](https://github.com/Homebrew/homebrew/pull/40876). Hopefully it will get merged in. I'm still working on binaries.

**Comment by mankoff** [comment]
rem is now available via homebrew

**Comment by kykim** [comment]
thanks for keeping track!
